version: '3.7'

services:
  node1:
    image: mongo
    ports:
      - 30001:27017
    volumes:
      - $HOME/mongoclusterdata/node1:/data/db
    networks:
      - mongocluster
    command: mongod --replSet comments
  node2:
    image: mongo
    ports:
      - 30002:27017
    volumes:
      - $HOME/mongoclusterdata/node2:/data/db
    networks:
      - mongocluster
    command: mongod --replSet comments
    depends_on :
      - node1
  node3:
    image: mongo
    ports:
      - 30003:27017
    volumes:
      - $HOME/mongoclusterdata/node3:/data/db
    networks:
      - mongocluster
    command: mongod --replSet comments
    depends_on :
        - node2
  mongo_app:
    image: mongo-app
    networks:
      - mongocluster
    ports:  
      - 8082:8082
# Added to /etc/hosts in container      
    extra_hosts:
      - "somehost:162.242.195.82"
      - "otherhost:50.31.209.229"      
networks:
  mongocluster:
    driver: bridge
